name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter Version Manager (FVM)
        run: |
          dart --version || sudo apt-get update -y && sudo apt-get install -y wget unzip xz-utils libglu1-mesa
          # Install Dart SDK (for activating FVM) if not present
          if ! command -v dart >/dev/null 2>&1; then
            DART_SDK_URL="https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip"
            wget -qO /tmp/dart.zip "$DART_SDK_URL"
            sudo unzip -q /tmp/dart.zip -d /opt
            echo "/opt/dart-sdk/bin" >> $GITHUB_PATH
          fi
          dart pub global activate fvm
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Cache pub and FVM
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            ~/.fvm
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}-fvm-${{ hashFiles('.fvm/**', '.fvmrc') }}

      - name: Install Flutter via FVM
        run: |
          fvm --version
          # Use version from project config; falls back to stable if missing
          if [ -f .fvm/fvm_config.json ]; then
            VERSION=$(jq -r '.flutterSdkVersion // empty' .fvm/fvm_config.json)
          elif [ -f .fvm/version ]; then
            VERSION=$(cat .fvm/version)
          else
            VERSION=stable
          fi
          fvm install "$VERSION"
          fvm flutter --version

      - name: Pub get (root and example)
        run: |
          fvm flutter pub get
          (cd example && fvm flutter pub get)

      - name: Analyze (root)
        run: fvm flutter analyze

      - name: Analyze (example)
        run: (cd example && fvm flutter analyze)

      - name: Run tests (root)
        run: fvm flutter test --no-pub

      - name: Run tests (example)
        run: (cd example && fvm flutter test --no-pub)
