name: Flutter CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3'
          channel: stable
          architecture: x64

      # Cache pub dependencies
      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}

      # Install dependencies (root + example)
      - name: Install dependencies
        run: |
          flutter pub get
          if [ -d "example" ]; then
            (cd example && flutter pub get)
          fi

      # Format (auto-fix instead of failing)
      - name: Format code (root and example)
        run: |
          dart format -o write .
          if [ -d "example" ]; then
            (cd example && dart format -o write . || true)
          fi

      # Analyze root (ignore infos/warnings, fail only on errors)
      - name: Analyze root
        run: flutter analyze --no-fatal-infos --no-fatal-warnings

      # Analyze example (ignore infos/warnings, fail only on errors)
      - name: Analyze example
        if: ${{ hashFiles('example/pubspec.yaml') != '' }}
        run: (cd example && flutter analyze --no-fatal-infos --no-fatal-warnings)

      # Run tests root
      - name: Run tests (root)
        run: flutter test --no-pub

      # Run tests example (if exists)
      - name: Run tests (example)
        if: ${{ hashFiles('example/pubspec.yaml') != '' }}
        run: (cd example && flutter test --no-pub)